apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: query-coordinator
  description: |
    Query Coordinator is a REST server that analyzes SoQL queries and
    dispatches them to an execution engine.
  links:
    - title: "Ops Doc"
      url: "https://socrata.atlassian.net/wiki/spaces/ONCALL/pages/2158985270/OpsDoc+-+SODA+Server+aka+NBE"
    - title: "New Backend (NBE) Crash Course"
      url: "https://tylertech.sharepoint.com/:v:/r/sites/DataInsightsDivision/Shared%20Documents/Engineering/NewBackendCrashCourse.mov?csf=1&web=1&e=2NsXHJ"
  annotations:
    github.com/project-slug: 'socrata-platform/query-coordinator'
    backstage.io/techdocs-ref: dir:.
    infrastructure: apps-marathon
spec:
  type: service
  owner: egress
  lifecycle: production
