#!/bin/sh
set -ev

CREDSFILE=/dev/shm/query-coordinator-cache-creds

if [ -e $CREDSFILE ]; then
    . $CREDSFILE
fi

if [ -z "$MARATHON_APP_ID" ]; then
    echo "Not running in marathon, so I will not compile the config template file!"
    echo "If you want to force config template compilation, set the \$MARATHON_APP_ID env var."
else
    echo "Compiling ${SERVER_CONFIG} file..."
    /bin/env_parse ${SERVER_CONFIG}.j2
fi

exec su socrata -c '/usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -Dconfig.file=${SERVER_CONFIG} \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
    -XX:+HeapDumpOnOutOfMemoryError \
    -XX:HeapDumpPath=/mnt/mesos/sandbox/query-coordinator-oom.hprof \
    -jar $SERVER_ARTIFACT'
